#!/usr/bin/env ash

# cpufreq ondemand|performance|...
if [ -f /sys/devices/system/cpu/cpufreq/policy0/scaling_available_governors ]; then
  governors="$(cat /sys/devices/system/cpu/cpufreq/policy0/scaling_available_governors)"
  if [ "$1" ]; then
    for i in $governors; do
      if [[ "$i" == "$1" ]]; then
        for i in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
          echo "$1" > "$i"
        done
      fi
    done
  else
    governors=$(echo $governors | sed s': :\|:g')
    echo "$0: <${governors%\|}>"
    echo -ne "\t"
    echo "- Governors available for use. Just pick up yours."
  fi
else
   echo "$FUNCNAME: no cpu governor found."
fi


