#!/usr/bin/env ash

[[ "$1" ]] || return 1

case "$1" in
  start)
    [ -f /dev/kvm ] && return 1
    modprobe -v kvm
    lsmod | grep kvm
    chmod o-rwx /dev/kvm
  ;;
  stop)
    [ -f /dev/kvm ] || return 1
    rmmod -v kvm
  ;;
  *)
    echo "Usage: ${0##*/} start|stop"
  ;;
esac


